/**
 * The 84 seeded products (spec 005 §2 "Dataset content", AC-6; `plan/10` §2.1; TASK-061).
 *
 * `plan/10` §2.1's split exactly: **40 bouquets, 14 arrangements, 8 plants, 10 funeral pieces,
 * 12 gift sets**, each carrying the six facets of §1.1 as keys and the attributes of that section
 * (stem count, vase flag, freshness days, allergen note, substitution class, `partner_only`).
 * Parsed under `ProductRegistrySchema` at module load, so a malformed row throws on first import
 * rather than at request time — the `src/config/countries.ts` precedent.
 *
 * **Names** follow `plan/10` §2.2's convention (an evocative name drawn from places, light and
 * seasons that travels across locales without translation) and are registered in
 * `content/i18n/glossary.en.md`'s "Product and tier names" row, as spec 005 §7 requires: the name
 * stays, the descriptor localises. They are content, not message keys — the only strings in this
 * dataset that are not keys, which is why the glossary row exists.
 *
 * **What is deliberately absent** (spec 005 §2, AC-6, and it is checked by
 * `tests/unit/catalogue-dataset.test.ts`, not merely intended): descriptions, SEO copy, imagery,
 * `de`/`pl` translations, reviews, partner payouts — and **prices**. A price is per destination
 * country and is authored in `prices.data.ts` by TASK-062; nothing in this file can carry an
 * amount, which is how "prices differ by destination and never by buyer" (EU 2018/302,
 * `plan/07` §3) stays a property of the shape rather than a rule someone remembers.
 *
 * Two authoring rulings, recorded because a later editor will need them:
 *
 *  - **Gift sets carry stem tiers, funeral pieces carry S/M/L** (spec 005 §13 Q4 answers "stem
 *    count where the product has one, S/M/L where a stem count is meaningless, single for
 *    plants", and names only bouquets/arrangements/plants). A gift set is a bouquet plus a gift,
 *    so its flowers do have a stem count; a wreath or a casket spray does not.
 *  - **`flowerTypes` and `colours` carry more than the primary.** spec 002 §5.1's `product` row
 *    stores `primary_flower` and `colour_primary` only, so the extra values are Phase 0 filter
 *    data for the read API (TASK-063) and are not projected — see `projections.ts`.
 */
import {
  type ProductData,
  ProductRegistrySchema,
  seededProductTypes,
} from "./schemas.ts";

/**
 * The authored rows, in SKU order (`FO-BQ-*` bouquets, `FO-AR-*` arrangements, `FO-PT-*` plants,
 * `FO-FN-*` funeral, `FO-GS-*` gift sets). `sku` is the natural key `plan/10` §4 upserts on.
 */
const products = [
  {
    sku: "FO-BQ-001",
    name: "Amber Hour",
    slug: "amber-hour",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "orange",
    colours: ["orange"],
    style: "classic",
    priceTier: "classic",
    occasions: ["birthday", "thank_you", "just_because"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-002",
    name: "Vistula Red",
    slug: "vistula-red",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "red",
    colours: ["red"],
    style: "classic",
    priceTier: "premium",
    occasions: ["romance", "anniversary", "valentines"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-003",
    name: "Baltic Dawn",
    slug: "baltic-dawn",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "modern",
    priceTier: "classic",
    occasions: ["birthday", "romance", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-004",
    name: "Quiet Blush",
    slug: "quiet-blush",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "minimal",
    priceTier: "essential",
    occasions: ["apology", "get_well", "just_because"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-005",
    name: "Northern Light",
    slug: "northern-light",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "premium",
    occasions: ["wedding", "anniversary", "congratulations"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-006",
    name: "Velvet Evening",
    slug: "velvet-evening",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "red",
    colours: ["red"],
    style: "luxury",
    priceTier: "luxury",
    occasions: ["romance", "valentines", "anniversary"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-007",
    name: "Rose Harbour",
    slug: "rose-harbour",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "classic",
    priceTier: "classic",
    occasions: ["birthday", "mothers_day", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-008",
    name: "Winter Rose",
    slug: "winter-rose",
    productType: "bouquet",
    primaryFlower: "roses",
    flowerTypes: ["roses", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["christmas", "new_year", "congratulations"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-009",
    name: "Kraków Spring",
    slug: "krakow-spring",
    productType: "bouquet",
    primaryFlower: "tulips",
    flowerTypes: ["tulips", "mixed"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["birthday", "easter", "just_because"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-010",
    name: "Sunday Market",
    slug: "sunday-market",
    productType: "bouquet",
    primaryFlower: "tulips",
    flowerTypes: ["tulips", "mixed"],
    colourPrimary: "yellow",
    colours: ["yellow"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["thank_you", "get_well", "easter"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-011",
    name: "First Thaw",
    slug: "first-thaw",
    productType: "bouquet",
    primaryFlower: "tulips",
    flowerTypes: ["tulips", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "classic",
    occasions: ["apology", "sympathy", "just_because"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-012",
    name: "Meadow Post",
    slug: "meadow-post",
    productType: "bouquet",
    primaryFlower: "tulips",
    flowerTypes: ["tulips", "mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["birthday", "mothers_day", "womens_day"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-013",
    name: "April Window",
    slug: "april-window",
    productType: "bouquet",
    primaryFlower: "tulips",
    flowerTypes: ["tulips", "mixed"],
    colourPrimary: "purple",
    colours: ["purple"],
    style: "modern",
    priceTier: "classic",
    occasions: ["birthday", "congratulations", "womens_day"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-014",
    name: "Tulip Parade",
    slug: "tulip-parade",
    productType: "bouquet",
    primaryFlower: "tulips",
    flowerTypes: ["tulips", "mixed"],
    colourPrimary: "vibrant",
    colours: ["vibrant", "orange", "pink"],
    style: "modern",
    priceTier: "classic",
    occasions: ["birthday", "graduation", "congratulations"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-015",
    name: "White Linen",
    slug: "white-linen",
    productType: "bouquet",
    primaryFlower: "lilies",
    flowerTypes: ["lilies", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["sympathy", "wedding", "anniversary"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 8,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-016",
    name: "Evening Chapel",
    slug: "evening-chapel",
    productType: "bouquet",
    primaryFlower: "lilies",
    flowerTypes: ["lilies", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["sympathy", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 8,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-017",
    name: "Snow Lantern",
    slug: "snow-lantern",
    productType: "bouquet",
    primaryFlower: "lilies",
    flowerTypes: ["lilies", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "classic",
    occasions: ["get_well", "sympathy"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 8,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-018",
    name: "Lily Terrace",
    slug: "lily-terrace",
    productType: "bouquet",
    primaryFlower: "lilies",
    flowerTypes: ["lilies", "mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "modern",
    priceTier: "premium",
    occasions: ["birthday", "anniversary", "mothers_day"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 8,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-019",
    name: "Peony Note",
    slug: "peony-note",
    productType: "bouquet",
    primaryFlower: "peonies",
    flowerTypes: ["peonies", "mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "luxury",
    priceTier: "luxury",
    occasions: ["romance", "anniversary", "wedding"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-020",
    name: "Soft June",
    slug: "soft-june",
    productType: "bouquet",
    primaryFlower: "peonies",
    flowerTypes: ["peonies", "mixed"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["birthday", "new_baby", "mothers_day"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-021",
    name: "Blush Terrace",
    slug: "blush-terrace",
    productType: "bouquet",
    primaryFlower: "peonies",
    flowerTypes: ["peonies", "mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "luxury",
    priceTier: "luxury",
    occasions: ["wedding", "romance"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-022",
    name: "Peony Hour",
    slug: "peony-hour",
    productType: "bouquet",
    primaryFlower: "peonies",
    flowerTypes: ["peonies", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "premium",
    occasions: ["wedding", "congratulations", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-023",
    name: "Field of Gold",
    slug: "field-of-gold",
    productType: "bouquet",
    primaryFlower: "sunflowers",
    flowerTypes: ["sunflowers", "mixed"],
    colourPrimary: "yellow",
    colours: ["yellow"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["birthday", "congratulations", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 9,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-024",
    name: "High Summer",
    slug: "high-summer",
    productType: "bouquet",
    primaryFlower: "sunflowers",
    flowerTypes: ["sunflowers", "mixed"],
    colourPrimary: "yellow",
    colours: ["yellow"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["just_because", "get_well", "housewarming"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 9,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-025",
    name: "Late Harvest",
    slug: "late-harvest",
    productType: "bouquet",
    primaryFlower: "sunflowers",
    flowerTypes: ["sunflowers", "mixed"],
    colourPrimary: "orange",
    colours: ["orange"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["thank_you", "housewarming", "retirement"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 9,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-026",
    name: "Bright Side",
    slug: "bright-side",
    productType: "bouquet",
    primaryFlower: "gerberas",
    flowerTypes: ["gerberas", "mixed"],
    colourPrimary: "vibrant",
    colours: ["vibrant", "orange", "pink"],
    style: "modern",
    priceTier: "essential",
    occasions: ["get_well", "birthday", "congratulations"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-027",
    name: "Carousel",
    slug: "carousel",
    productType: "bouquet",
    primaryFlower: "gerberas",
    flowerTypes: ["gerberas", "mixed"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "modern",
    priceTier: "essential",
    occasions: ["birthday", "graduation", "just_because"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-028",
    name: "Warsaw Morning",
    slug: "warsaw-morning",
    productType: "bouquet",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "classic",
    priceTier: "classic",
    occasions: ["birthday", "thank_you", "just_because"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-029",
    name: "Garden Letter",
    slug: "garden-letter",
    productType: "bouquet",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["apology", "get_well", "thank_you"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-030",
    name: "Late Summer Table",
    slug: "late-summer-table",
    productType: "bouquet",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "orange",
    colours: ["orange"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["housewarming", "thank_you", "retirement"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-031",
    name: "Pastel Weekend",
    slug: "pastel-weekend",
    productType: "bouquet",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "minimal",
    priceTier: "essential",
    occasions: ["new_baby", "get_well", "just_because"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-032",
    name: "Painter's Table",
    slug: "painters-table",
    productType: "bouquet",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "vibrant",
    colours: ["vibrant", "orange", "pink"],
    style: "modern",
    priceTier: "premium",
    occasions: ["birthday", "congratulations", "graduation"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-033",
    name: "Long Weekend",
    slug: "long-weekend",
    productType: "bouquet",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["just_because", "thank_you"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-034",
    name: "Season's Hand",
    slug: "seasons-hand",
    productType: "bouquet",
    primaryFlower: "seasonal",
    flowerTypes: ["seasonal"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["just_because", "birthday"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-035",
    name: "Harvest Light",
    slug: "harvest-light",
    productType: "bouquet",
    primaryFlower: "seasonal",
    flowerTypes: ["seasonal"],
    colourPrimary: "orange",
    colours: ["orange"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["housewarming", "thank_you"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-036",
    name: "Winter Table",
    slug: "winter-table",
    productType: "bouquet",
    primaryFlower: "seasonal",
    flowerTypes: ["seasonal"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["christmas", "new_year"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-037",
    name: "Spring Post",
    slug: "spring-post",
    productType: "bouquet",
    primaryFlower: "seasonal",
    flowerTypes: ["seasonal"],
    colourPrimary: "yellow",
    colours: ["yellow"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["easter", "womens_day", "mothers_day"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-038",
    name: "Old Town",
    slug: "old-town",
    productType: "bouquet",
    primaryFlower: "carnations",
    flowerTypes: ["carnations", "mixed"],
    colourPrimary: "red",
    colours: ["red"],
    style: "classic",
    priceTier: "essential",
    occasions: ["birthday", "name_day", "just_because"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-039",
    name: "Blue Hour",
    slug: "blue-hour",
    productType: "bouquet",
    primaryFlower: "hydrangeas",
    flowerTypes: ["hydrangeas", "mixed"],
    colourPrimary: "blue",
    colours: ["blue"],
    style: "modern",
    priceTier: "premium",
    occasions: ["anniversary", "congratulations", "housewarming"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 5,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-BQ-040",
    name: "Morning Scent",
    slug: "morning-scent",
    productType: "bouquet",
    primaryFlower: "freesias",
    flowerTypes: ["freesias", "mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "classic",
    occasions: ["get_well", "thank_you", "apology"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-001",
    name: "Small Kindness",
    slug: "small-kindness",
    productType: "arrangement",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "minimal",
    priceTier: "essential",
    occasions: ["get_well", "apology", "just_because"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-002",
    name: "Mantelpiece",
    slug: "mantelpiece",
    productType: "arrangement",
    primaryFlower: "roses",
    flowerTypes: ["roses"],
    colourPrimary: "red",
    colours: ["red"],
    style: "classic",
    priceTier: "premium",
    occasions: ["anniversary", "romance"],
    substitutionClass: "main_flower",
    vaseIncluded: true,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-003",
    name: "Welcome Home",
    slug: "welcome-home",
    productType: "arrangement",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["housewarming", "congratulations", "new_baby"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-004",
    name: "Desk Bloom",
    slug: "desk-bloom",
    productType: "arrangement",
    primaryFlower: "gerberas",
    flowerTypes: ["gerberas"],
    colourPrimary: "vibrant",
    colours: ["vibrant", "orange", "pink"],
    style: "modern",
    priceTier: "essential",
    occasions: ["congratulations", "birthday", "thank_you"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-005",
    name: "Paper Window",
    slug: "paper-window",
    productType: "arrangement",
    primaryFlower: "tulips",
    flowerTypes: ["tulips"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "minimal",
    priceTier: "essential",
    occasions: ["birthday", "womens_day", "just_because"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-006",
    name: "Glass Morning",
    slug: "glass-morning",
    productType: "arrangement",
    primaryFlower: "lilies",
    flowerTypes: ["lilies"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["sympathy", "thank_you", "wedding"],
    substitutionClass: "main_flower",
    vaseIncluded: true,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-007",
    name: "Kitchen Table",
    slug: "kitchen-table",
    productType: "arrangement",
    primaryFlower: "seasonal",
    flowerTypes: ["seasonal"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["housewarming", "thank_you"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-008",
    name: "Hallway Light",
    slug: "hallway-light",
    productType: "arrangement",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "modern",
    priceTier: "classic",
    occasions: ["housewarming", "congratulations"],
    substitutionClass: "florists_choice",
    vaseIncluded: true,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-009",
    name: "Reading Corner",
    slug: "reading-corner",
    productType: "arrangement",
    primaryFlower: "freesias",
    flowerTypes: ["freesias"],
    colourPrimary: "purple",
    colours: ["purple"],
    style: "minimal",
    priceTier: "classic",
    occasions: ["get_well", "retirement", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-010",
    name: "Studio Vase",
    slug: "studio-vase",
    productType: "arrangement",
    primaryFlower: "peonies",
    flowerTypes: ["peonies"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "luxury",
    priceTier: "luxury",
    occasions: ["anniversary", "wedding", "romance"],
    substitutionClass: "main_flower",
    vaseIncluded: true,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-011",
    name: "Garden Crate",
    slug: "garden-crate",
    productType: "arrangement",
    primaryFlower: "seasonal",
    flowerTypes: ["seasonal"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["housewarming", "thank_you", "easter"],
    substitutionClass: "florists_choice",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-012",
    name: "White Cube",
    slug: "white-cube",
    productType: "arrangement",
    primaryFlower: "roses",
    flowerTypes: ["roses"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "premium",
    occasions: ["wedding", "congratulations", "sympathy"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-013",
    name: "Copper Bowl",
    slug: "copper-bowl",
    productType: "arrangement",
    primaryFlower: "chrysanthemums",
    flowerTypes: ["chrysanthemums"],
    colourPrimary: "orange",
    colours: ["orange"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["all_saints", "thank_you", "housewarming"],
    substitutionClass: "colour_scheme",
    vaseIncluded: true,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-AR-014",
    name: "Linen Basket",
    slug: "linen-basket",
    productType: "arrangement",
    primaryFlower: "alstroemeria",
    flowerTypes: ["alstroemeria"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["new_baby", "get_well", "birthday"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-001",
    name: "Moth Orchid White",
    slug: "moth-orchid-white",
    productType: "plant",
    primaryFlower: "orchids",
    flowerTypes: ["orchids"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "premium",
    occasions: ["housewarming", "congratulations", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-002",
    name: "Moth Orchid Pink",
    slug: "moth-orchid-pink",
    productType: "plant",
    primaryFlower: "orchids",
    flowerTypes: ["orchids"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "minimal",
    priceTier: "premium",
    occasions: ["birthday", "mothers_day", "thank_you"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-003",
    name: "Twin Orchid",
    slug: "twin-orchid",
    productType: "plant",
    primaryFlower: "orchids",
    flowerTypes: ["orchids"],
    colourPrimary: "white",
    colours: ["white"],
    style: "luxury",
    priceTier: "luxury",
    occasions: ["wedding", "anniversary", "retirement"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-004",
    name: "Peace Lily",
    slug: "peace-lily",
    productType: "plant",
    primaryFlower: "lilies",
    flowerTypes: ["lilies"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "classic",
    occasions: ["sympathy", "housewarming", "get_well"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-005",
    name: "Anthurium",
    slug: "anthurium",
    productType: "plant",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "red",
    colours: ["red"],
    style: "modern",
    priceTier: "classic",
    occasions: ["housewarming", "congratulations"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-006",
    name: "Olive Sapling",
    slug: "olive-sapling",
    productType: "plant",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "premium",
    occasions: ["housewarming", "wedding", "retirement"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-007",
    name: "Jasmine Pot",
    slug: "jasmine-pot",
    productType: "plant",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["get_well", "thank_you", "just_because"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-PT-008",
    name: "Azalea Pot",
    slug: "azalea-pot",
    productType: "plant",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "classic",
    priceTier: "essential",
    occasions: ["birthday", "mothers_day", "get_well"],
    substitutionClass: "main_flower",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 30,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-001",
    name: "Farewell Wreath",
    slug: "farewell-wreath",
    productType: "funeral",
    primaryFlower: "chrysanthemums",
    flowerTypes: ["chrysanthemums"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["sympathy", "all_saints"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-002",
    name: "Standing Spray",
    slug: "standing-spray",
    productType: "funeral",
    primaryFlower: "lilies",
    flowerTypes: ["lilies"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["sympathy"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-003",
    name: "Casket Spray",
    slug: "casket-spray",
    productType: "funeral",
    primaryFlower: "lilies",
    flowerTypes: ["lilies"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "luxury",
    occasions: ["sympathy"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-004",
    name: "White Heart",
    slug: "white-heart",
    productType: "funeral",
    primaryFlower: "roses",
    flowerTypes: ["roses"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "luxury",
    occasions: ["sympathy"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-005",
    name: "Sympathy Basket",
    slug: "sympathy-basket",
    productType: "funeral",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "classic",
    occasions: ["sympathy"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-006",
    name: "Grave Bouquet",
    slug: "grave-bouquet",
    productType: "funeral",
    primaryFlower: "chrysanthemums",
    flowerTypes: ["chrysanthemums"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "essential",
    occasions: ["sympathy", "all_saints"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-007",
    name: "Memorial Cross",
    slug: "memorial-cross",
    productType: "funeral",
    primaryFlower: "chrysanthemums",
    flowerTypes: ["chrysanthemums"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "premium",
    occasions: ["sympathy", "all_saints"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-008",
    name: "Quiet Wreath",
    slug: "quiet-wreath",
    productType: "funeral",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "minimal",
    priceTier: "classic",
    occasions: ["sympathy"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-009",
    name: "Condolence Bouquet",
    slug: "condolence-bouquet",
    productType: "funeral",
    primaryFlower: "roses",
    flowerTypes: ["roses"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "classic",
    occasions: ["sympathy"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-FN-010",
    name: "Stone Garden",
    slug: "stone-garden",
    productType: "funeral",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "white",
    colours: ["white"],
    style: "minimal",
    priceTier: "premium",
    occasions: ["sympathy", "all_saints"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: null,
    freshnessDays: 5,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-001",
    name: "Amber Hour + Chocolates",
    slug: "amber-hour-chocolates",
    productType: "gift_set",
    primaryFlower: "roses",
    flowerTypes: ["roses"],
    colourPrimary: "orange",
    colours: ["orange"],
    style: "classic",
    priceTier: "premium",
    occasions: ["birthday", "thank_you"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: true,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-002",
    name: "Baltic Dawn + Vase",
    slug: "baltic-dawn-vase",
    productType: "gift_set",
    primaryFlower: "roses",
    flowerTypes: ["roses"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "classic",
    priceTier: "premium",
    occasions: ["birthday", "romance", "anniversary"],
    substitutionClass: "colour_scheme",
    vaseIncluded: true,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-003",
    name: "Welcome Baby Blue + Plush",
    slug: "welcome-baby-blue-plush",
    productType: "gift_set",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "blue",
    colours: ["blue"],
    style: "classic",
    priceTier: "classic",
    occasions: ["new_baby", "congratulations"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-004",
    name: "Welcome Baby Pink + Plush",
    slug: "welcome-baby-pink-plush",
    productType: "gift_set",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "classic",
    priceTier: "classic",
    occasions: ["new_baby", "congratulations"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-005",
    name: "Kraków Spring + Chocolates",
    slug: "krakow-spring-chocolates",
    productType: "gift_set",
    primaryFlower: "tulips",
    flowerTypes: ["tulips"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["birthday", "easter", "womens_day"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 25,
    freshnessDays: 7,
    allergenNote: true,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-006",
    name: "Quiet Blush + Vase",
    slug: "quiet-blush-vase",
    productType: "gift_set",
    primaryFlower: "roses",
    flowerTypes: ["roses"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "minimal",
    priceTier: "classic",
    occasions: ["apology", "get_well"],
    substitutionClass: "colour_scheme",
    vaseIncluded: true,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-007",
    name: "Field of Gold + Chocolates",
    slug: "field-of-gold-chocolates",
    productType: "gift_set",
    primaryFlower: "sunflowers",
    flowerTypes: ["sunflowers"],
    colourPrimary: "yellow",
    colours: ["yellow"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["birthday", "congratulations"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 9,
    freshnessDays: 7,
    allergenNote: true,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-008",
    name: "Peony Note + Vase",
    slug: "peony-note-vase",
    productType: "gift_set",
    primaryFlower: "peonies",
    flowerTypes: ["peonies"],
    colourPrimary: "pink",
    colours: ["pink"],
    style: "luxury",
    priceTier: "luxury",
    occasions: ["anniversary", "romance", "wedding"],
    substitutionClass: "colour_scheme",
    vaseIncluded: true,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-009",
    name: "Warsaw Morning + Balloon",
    slug: "warsaw-morning-balloon",
    productType: "gift_set",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "mixed",
    colours: ["mixed"],
    style: "classic",
    priceTier: "classic",
    occasions: ["birthday", "congratulations"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-010",
    name: "Bright Side + Balloon",
    slug: "bright-side-balloon",
    productType: "gift_set",
    primaryFlower: "gerberas",
    flowerTypes: ["gerberas"],
    colourPrimary: "vibrant",
    colours: ["vibrant", "orange", "pink"],
    style: "modern",
    priceTier: "classic",
    occasions: ["get_well", "birthday", "graduation"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 15,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-011",
    name: "White Linen + Chocolates",
    slug: "white-linen-chocolates",
    productType: "gift_set",
    primaryFlower: "lilies",
    flowerTypes: ["lilies"],
    colourPrimary: "white",
    colours: ["white"],
    style: "classic",
    priceTier: "luxury",
    occasions: ["anniversary", "thank_you"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 8,
    freshnessDays: 7,
    allergenNote: true,
    partnerOnly: false,
    status: "active",
  },
  {
    sku: "FO-GS-012",
    name: "Garden Letter + Plush",
    slug: "garden-letter-plush",
    productType: "gift_set",
    primaryFlower: "mixed",
    flowerTypes: ["mixed"],
    colourPrimary: "pastel",
    colours: ["pastel", "pink", "white"],
    style: "rustic",
    priceTier: "classic",
    occasions: ["new_baby", "get_well"],
    substitutionClass: "colour_scheme",
    vaseIncluded: false,
    stemCount: 18,
    freshnessDays: 7,
    allergenNote: false,
    partnerOnly: false,
    status: "active",
  },
] as const;

/** Parsed at module load: a malformed dataset throws on first import, never at request time. */
export const PRODUCTS: readonly ProductData[] =
  ProductRegistrySchema.parse(products);

/** `plan/10` §2.1's split, as a value the dataset test and `catalogue:check` both read. */
export const SEEDED_PRODUCT_COUNTS: Readonly<
  Record<(typeof seededProductTypes)[number], number>
> = {
  bouquet: 40,
  arrangement: 14,
  plant: 8,
  funeral: 10,
  gift_set: 12,
};

/** Look a product up by its SKU. Throws on an unknown SKU: the set is closed data. */
export function productBySku(sku: string): ProductData {
  const product = PRODUCTS.find((candidate) => candidate.sku === sku);
  if (product === undefined) {
    throw new Error(`unknown product sku: ${sku}`);
  }
  return product;
}
