/**
 * Playwright harness (spec 001 §2 "Testing harness", §7, §8, AC-17, TASK-008).
 *
 * One config, five projects, three scripts:
 *   `pnpm test:e2e`    -> `e2e-desktop` + `e2e-mobile`  (tests/e2e/**)
 *   `pnpm test:visual` -> `visual` (`/`, `/en`, `/de`) + `pseudo-rtl` (`/ar-XB`)
 *   `pnpm test:a11y`   -> `a11y`                        (tests/a11y/**)
 *
 * `baseURL` comes from `PLAYWRIGHT_BASE_URL`: the Vercel preview URL in CI (from the `preview`
 * job's output), `http://localhost:3000` locally against `pnpm build && pnpm start`. There is
 * deliberately no `webServer`: the target is a deployment, not a dev server, and a preview is
 * what AC-17 asks the suites to run against.
 *
 * Previews are behind Vercel Deployment Protection (AC-29), so every request carries
 * `x-vercel-protection-bypass` when `VERCEL_AUTOMATION_BYPASS_SECRET` is set, together with
 * `x-vercel-set-bypass-cookie: false` — without the latter Vercel answers with a `_vercel_jwt`
 * cookie and AC-15's "zero `Set-Cookie` on `/`" assertion would fail on the harness, not on the
 * application.
 */
import { defineConfig, devices } from "@playwright/test";

const baseURL = process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:3000";
const bypassSecret = process.env.VERCEL_AUTOMATION_BYPASS_SECRET;
const isCI = process.env.CI === "true" || process.env.CI === "1";

/**
 * The RTL project. It stopped being a stub at TASK-042: it navigates `/ar-XB`, a real
 * `dir="rtl"` document served from the generated pseudo-locale, so the init script that used to
 * force `dir="rtl"` in the browser (`tests/visual/pseudo-rtl.ts`) is deleted (spec 003 AC-30).
 * Each project screenshots its own spec file, so no test has to ask which project it is in.
 */
export const PSEUDO_RTL_PROJECT = "pseudo-rtl";

const protectionBypassHeaders: Record<string, string> =
  bypassSecret === undefined || bypassSecret === ""
    ? {}
    : {
        "x-vercel-protection-bypass": bypassSecret,
        "x-vercel-set-bypass-cookie": "false",
      };

export default defineConfig({
  testDir: "tests",
  // Playwright resolves specs itself; see the comment in that file for why the `@/*` alias is
  // restated there.
  tsconfig: "./tests/tsconfig.playwright.json",
  // Only Playwright specs: `tests/unit/**` and `tests/integration/**` are Vitest's `*.test.ts`.
  testMatch: "**/*.spec.ts",
  fullyParallel: true,
  forbidOnly: isCI,
  retries: isCI ? 1 : 0,
  reporter: isCI
    ? [["github"], ["html", { open: "never" }], ["list"]]
    : [["list"]],
  timeout: 30_000,
  expect: {
    // spec 001 §2: visual screenshots at a 0.1 % threshold.
    toHaveScreenshot: {
      maxDiffPixelRatio: 0.001,
      animations: "disabled",
      caret: "hide",
    },
  },
  // `{platform}` is back (TASK-035). It was dropped in TASK-008 because the Phase 0 shell had no
  // text, no fonts and no images, so one baseline was byte-identical on the macOS machine that
  // generated it and on the Linux runner that verified it. Spec 003 gives `/` a heading, an intro
  // and four locale links, and text is rendered by the host's font stack and rasteriser: a macOS
  // baseline differs from a Linux one by far more than the 0.1 % threshold. Per-platform
  // baselines keep the gate honest instead of loosening the threshold until it stops catching
  // regressions. `{projectName}` still keeps `visual` and `pseudo-rtl` apart.
  //
  // Both baselines are committed. `darwin/` is generated locally
  // (`pnpm test:visual --update-snapshots`); `linux/` is generated by the `visual` CI job, which
  // uploads `tests/visual/__screenshots__/` in its failure artifact for exactly that purpose —
  // push, let the job write the missing baseline, download it, commit it. CI itself never passes
  // `--update-snapshots`, so a missing or changed baseline still fails the job.
  snapshotPathTemplate:
    "{testDir}/{testFileDir}/__screenshots__/{projectName}/{platform}/{arg}{ext}",
  use: {
    baseURL,
    extraHTTPHeaders: protectionBypassHeaders,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    ignoreHTTPSErrors: false,
  },
  projects: [
    {
      name: "e2e-desktop",
      testMatch: "e2e/**/*.spec.ts",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      name: "e2e-mobile",
      testMatch: "e2e/**/*.spec.ts",
      use: { ...devices["Pixel 7"] },
    },
    {
      name: "visual",
      // Every LTR visual spec (`/`, `/en`, `/de` in `shell.spec.ts`; the colophon's four element
      // baselines in `footer.spec.ts`, TASK-049). `/ar-XB` belongs to the project below, so the
      // RTL spec is the one file ignored here — a glob per file would make every 004 task that
      // adds a template edit this config.
      testMatch: "visual/*.spec.ts",
      testIgnore: "visual/pseudo-rtl.spec.ts",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 1280, height: 720 },
      },
    },
    {
      // `/ar-XB` and nothing else: the real RTL gate of spec 003 AC-30.
      name: PSEUDO_RTL_PROJECT,
      testMatch: "visual/pseudo-rtl.spec.ts",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 1280, height: 720 },
      },
    },
    {
      name: "a11y",
      testMatch: "a11y/**/*.spec.ts",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
