/**
 * T-14's contract half: spec 001's `validate-sitemap` CLI against **this repository's real
 * sitemap** (spec 007 §2 "Sitemaps", §11, AC-13, AC-14; TASK-094).
 *
 * `tests/unit/seo-validate-sitemap.test.ts` proves the CLI works on hand-made cases. What is
 * contracted here is the other direction: the documents `/sitemap.xml` will serve satisfy the
 * gate, and the gate would notice if they stopped. So every case runs over a **copy** of the
 * committed set (`tests/fixtures/seo/sitemap/`, generated by
 * `scripts/seo/generate-sitemap-fixtures.ts`): clean it passes, tampered in the two ways that
 * matter it fails, and the working tree is never touched.
 *
 * The two tampering cases are the two failures `plan/02` §10 exists to prevent: a `noindex` URL
 * in a sitemap, and a `<loc>` a crawler will not follow.
 */
import { execFileSync } from "node:child_process";
import {
  cpSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { describe, expect, it } from "vitest";

const repoRoot = resolve(__dirname, "../..");
const committed = join(repoRoot, "tests/fixtures/seo/sitemap");

interface CliResult {
  readonly status: number;
  readonly stdout: string;
  readonly stderr: string;
}

function validate(dir: string): CliResult {
  try {
    const stdout = execFileSync(
      process.execPath,
      ["scripts/seo/validate-sitemap.ts", "--dir", dir],
      { cwd: repoRoot, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
    );
    return { status: 0, stdout, stderr: "" };
  } catch (error) {
    const failure = error as {
      status?: number;
      stdout?: string;
      stderr?: string;
    };
    return {
      status: failure.status ?? 1,
      stdout: failure.stdout ?? "",
      stderr: failure.stderr ?? "",
    };
  }
}

/** A throwaway copy of the committed set, so a tampering case cannot dirty the tree. */
function withCopy<T>(fn: (dir: string) => T): T {
  const dir = mkdtempSync(join(tmpdir(), "fo-sitemap-contract-"));
  try {
    cpSync(committed, dir, { recursive: true });
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const CHILD = "en-corridors.xml";

describe("validate-sitemap over the real URL set (AC-13, T-14)", () => {
  it("passes on the committed sitemap tree", () => {
    const result = withCopy(validate);
    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
    expect(result.stdout).toMatch(/\d+ fixture\(s\) ok/u);
  });

  it("fails when a URL the engine marks noindex is added to a child (AC-14)", () => {
    const result = withCopy((dir) => {
      const path = join(dir, CHILD);
      const noindex = (
        JSON.parse(readFileSync(join(dir, "noindex.json"), "utf8")) as {
          noindex: string[];
        }
      ).noindex[0];
      expect(noindex).toBeDefined();
      writeFileSync(
        path,
        readFileSync(path, "utf8").replace(
          "</urlset>",
          `  <url>\n    <loc>${noindex ?? ""}</loc>\n    <lastmod>2026-09-18</lastmod>\n  </url>\n</urlset>`,
        ),
        "utf8",
      );
      return validate(dir);
    });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("must not be in a sitemap");
  });

  it("fails when a <loc> stops being an absolute https URL", () => {
    const result = withCopy((dir) => {
      const path = join(dir, CHILD);
      writeFileSync(
        path,
        readFileSync(path, "utf8").replace("<loc>https://", "<loc>http://"),
        "utf8",
      );
      return validate(dir);
    });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("must be https://");
  });
});
