/**
 * Section-anchored spec indexes — AC-35 / T-36 (spec 001 §14 A15, TASK-086).
 *
 * A spec is 40–100 KB and an agent needs three of its sections. `## 0. Index` sits directly under
 * the header table of every spec and lists each `AC-n` and `T-n` with the section it is defined in
 * and its line number (`§9 L244`), so a reader can open the spec at the right offset instead of
 * loading the whole file.
 *
 * The definition of an id is the line that introduces it — `- **AC-1** …` in the acceptance
 * criteria, `| T-01 | …` in the test-case table, or a bolded id in a §14 amendment — and the first
 * mention anywhere is the fallback. Line numbers are those of the file *with* the index in it, so
 * the generator iterates to a fixed point before writing.
 *
 * `pnpm specs:index` rewrites every block, `pnpm specs:index --check` fails when one is stale.
 * `tests/unit/specs-index.test.ts` drives the pure functions.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const SPECS_DIR = "specs";
/** The index heading, inserted after the header table. */
export const INDEX_HEADING = "## 0. Index";
/** The end marker; everything between the heading and it is generated. */
export const INDEX_END = "<!-- /index -->";
/** Files under `specs/` that are not specs. */
export const NOT_A_SPEC = ["README.md", "_template.md"] as const;

export interface Anchor {
  readonly id: string;
  /** The `§` label of the section the id is defined in. */
  readonly section: string;
  /** 1-based line number in the file the index is rendered into. */
  readonly line: number;
}

/** `## 9. Acceptance criteria` → `§9`; a heading without a number keeps its text. */
export function sectionLabel(heading: string): string {
  const text = heading.replace(/^#+\s*/, "").trim();
  const numbered = /^(\d+)\./.exec(text);
  return numbered?.[1] === undefined ? `§${text}` : `§${numbered[1]}`;
}

const ID_PATTERN = /\b(AC|T)-(\d+)\b/g;

function isDefinition(line: string, id: string): boolean {
  const escaped = id.replace("-", "-");
  return (
    new RegExp(`^\\s*[-*]\\s*\\*\\*${escaped}\\b`).test(line) ||
    new RegExp(`^\\s*\\*\\*${escaped}\\b`).test(line) ||
    new RegExp(`^\\|\\s*\\*?\\*?${escaped}\\b`).test(line) ||
    new RegExp(`^\\s*${escaped}\\s+[—-]`).test(line)
  );
}

/**
 * Every `AC-n` and `T-n` in the document with the section and line of its definition (or of its
 * first mention when nothing looks like a definition).
 */
export function anchorsIn(markdown: string): Anchor[] {
  const lines = markdown.split("\n");
  const first = new Map<string, Anchor>();
  const defined = new Map<string, Anchor>();
  let section = "§?";
  lines.forEach((line, index) => {
    if (line.startsWith("## ")) section = sectionLabel(line);
    for (const match of line.matchAll(ID_PATTERN)) {
      const id = `${match[1] ?? ""}-${match[2] ?? ""}`;
      const anchor: Anchor = { id, section, line: index + 1 };
      if (!first.has(id)) first.set(id, anchor);
      if (!defined.has(id) && isDefinition(line, id)) defined.set(id, anchor);
    }
  });
  const ids = [...first.keys()];
  return ids
    .map((id) => defined.get(id) ?? first.get(id))
    .filter((anchor): anchor is Anchor => anchor !== undefined)
    .sort((a, b) => {
      if (a.id.startsWith("AC") !== b.id.startsWith("AC")) {
        return a.id.startsWith("AC") ? -1 : 1;
      }
      return numberOf(a.id) - numberOf(b.id);
    });
}

function numberOf(id: string): number {
  return Number.parseInt(id.split("-")[1] ?? "0", 10);
}

function renderList(anchors: readonly Anchor[]): string {
  return anchors.length === 0
    ? "_none yet_"
    : anchors
        .map(
          (anchor) =>
            `\`${anchor.id}\` ${anchor.section} L${String(anchor.line)}`,
        )
        .join(" · ");
}

/** The index block, heading and end marker included. */
export function renderIndex(anchors: readonly Anchor[]): string {
  const acs = anchors.filter((anchor) => anchor.id.startsWith("AC-"));
  const tests = anchors.filter((anchor) => anchor.id.startsWith("T-"));
  return [
    INDEX_HEADING,
    "",
    "<!-- generated by `pnpm specs:index`; edit the sections, not this block. Line numbers are of",
    "     this file, so re-run the script after any edit that moves them. -->",
    "",
    `**Acceptance criteria** — ${renderList(acs)}`,
    "",
    `**Test cases** — ${renderList(tests)}`,
    "",
    INDEX_END,
  ].join("\n");
}

/** The 0-based line index where the index block starts: after the header table. */
export function insertionPoint(lines: readonly string[]): number {
  let tableEnd = -1;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (line.startsWith("|")) tableEnd = index;
    else if (tableEnd !== -1) break;
  }
  return tableEnd === -1 ? 1 : tableEnd + 1;
}

/** The document with its index block removed, so it can be regenerated. */
export function withoutIndex(markdown: string): string {
  const start = markdown.indexOf(`${INDEX_HEADING}\n`);
  if (start === -1) return markdown;
  const end = markdown.indexOf(INDEX_END, start);
  if (end === -1) return markdown;
  const after = end + INDEX_END.length;
  return `${markdown.slice(0, start)}${markdown.slice(after).replace(/^\n+/, "")}`;
}

/**
 * The document with a current index block. The anchors are read from the document *without* the
 * block — so the block never indexes itself — and then shifted by the block's own height, which is
 * found by rendering once and re-rendering with the shifted lines.
 */
export function withIndex(markdown: string): string {
  const base = withoutIndex(markdown);
  const lines = base.split("\n");
  const at = insertionPoint(lines);
  const anchors = anchorsIn(base);
  let height = renderIndex(anchors).split("\n").length + 1;
  for (let pass = 0; pass < 3; pass += 1) {
    const shift = height;
    const block = renderIndex(
      anchors.map((anchor) =>
        anchor.line - 1 >= at
          ? { ...anchor, line: anchor.line + shift }
          : anchor,
      ),
    );
    const next = block.split("\n").length + 1;
    if (next === height) {
      return [
        ...lines.slice(0, at),
        "",
        ...block.split("\n"),
        ...lines.slice(at),
      ].join("\n");
    }
    height = next;
  }
  throw new Error("specs index: block height did not settle");
}

/** Every spec file under `specs/`, repository-relative and sorted. */
export function specFiles(root: string): string[] {
  const skip: ReadonlySet<string> = new Set(NOT_A_SPEC);
  return readdirSync(join(root, SPECS_DIR))
    .filter((name) => name.endsWith(".md") && !skip.has(name))
    .sort()
    .map((name) => `${SPECS_DIR}/${name}`);
}

/** Stale or missing index blocks (empty = healthy). */
export function checkSpecIndexes(root: string): string[] {
  const problems: string[] = [];
  for (const file of specFiles(root)) {
    const markdown = readFileSync(join(root, file), "utf8");
    if (!markdown.includes(INDEX_HEADING)) {
      problems.push(
        `${file}: no "${INDEX_HEADING}" block — run \`pnpm specs:index\``,
      );
      continue;
    }
    if (withIndex(markdown) !== markdown) {
      problems.push(`${file}: index is stale — run \`pnpm specs:index\``);
    }
  }
  const template = join(root, SPECS_DIR, "_template.md");
  if (!readFileSync(template, "utf8").includes(INDEX_HEADING)) {
    problems.push(
      `${SPECS_DIR}/_template.md: the template must carry the "${INDEX_HEADING}" block`,
    );
  }
  return problems;
}

/** Rewrites every spec's index; returns the files it changed. */
export function writeSpecIndexes(root: string): string[] {
  const changed: string[] = [];
  for (const file of specFiles(root)) {
    const path = join(root, file);
    const markdown = readFileSync(path, "utf8");
    const next = withIndex(markdown);
    if (next !== markdown) {
      writeFileSync(path, next, "utf8");
      changed.push(file);
    }
  }
  return changed;
}

const isMain =
  typeof process.argv[1] === "string" &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  const args = process.argv.slice(2);
  const root = resolve(
    args.find((arg) => !arg.startsWith("--")) ?? process.cwd(),
  );
  if (args.includes("--check")) {
    const problems = checkSpecIndexes(root);
    if (problems.length > 0) {
      for (const problem of problems)
        process.stderr.write(`specs index: ${problem}\n`);
      process.exit(1);
    }
    process.stdout.write(
      `specs index ok: ${String(specFiles(root).length)} spec(s) indexed\n`,
    );
  } else {
    const changed = writeSpecIndexes(root);
    process.stdout.write(
      changed.length === 0
        ? "specs index: already current\n"
        : `specs index: rewrote ${changed.join(", ")}\n`,
    );
  }
}
