/**
 * The wordmark, outlined (spec 004 §14 A21 clause 3; TASK-175).
 *
 * The logo stays exactly as it ships — the trading name in Newsreader 500, tracked 0.04em — but no
 * Newsreader file is loaded any more, so the letters are paths (`wordmark-paths.ts`, generated by
 * `pnpm fonts:wordmark`) filled with `--color-logo-ink`, the logo's own token, which v2 does not
 * re-colour. Inline, so it is part of the cached HTML with no request; never mirrored in RTL.
 *
 * Sized by its block size (`className`, e.g. `h-[19px] md:h-[25px]`, the chrome artboards' 19 and
 * 25 px); the inline size follows from the view box. Decorative when the link around it is
 * already named; `label` (the trading name, from `company.ts`) makes it `role="img"` for the case
 * that needs a name. The header and footer swap onto it in TASK-176.
 */
import type { ReactElement } from "react";

import { WORDMARK_PATH, WORDMARK_VIEW_BOX } from "./wordmark-paths.ts";

export interface WordmarkProps {
  /** Accessible name. Omit when a sibling or the surrounding link already names it. */
  readonly label?: string;
  readonly className?: string;
}

export function Wordmark({ label, className }: WordmarkProps): ReactElement {
  return (
    <svg
      viewBox={WORDMARK_VIEW_BOX}
      className={["inline-block w-auto", className].filter(Boolean).join(" ")}
      focusable="false"
      data-fo-wordmark
      {...(label === undefined
        ? { "aria-hidden": true }
        : { role: "img", "aria-label": label })}
    >
      <path d={WORDMARK_PATH} fill="var(--color-logo-ink)" />
    </svg>
  );
}
